export const strings = {
  eyebrow: 'Playground',
  stripe: '',
  titleLead: 'Probe one',
  titleStrong: 'account path.',
  intro: 'Run one prompt through the router.',
  formTitle: 'Run input',
  resultTitle: 'Run result',
  resultMetaIdle: 'waiting',
  resultMetaDone: 'complete',
  resultMetaError: 'failed',
  noActiveAccounts: 'No active accounts.',
  charCounter: 'chars',
  defaultModel: 'gpt-5.4-mini',
  labels: {
    mode: 'Selection mode',
    endpoint: 'Endpoint',
    account: 'Account',
    authMethod: 'Auth method',
    sessionKey: 'Session key',
    model: 'Model',
    maxOutputTokens: 'Max output',
    includeRaw: 'Include raw JSON',
    prompt: 'Prompt',
    selectedAccount: 'Selected account',
    outcome: 'Outcome',
    latency: 'Latency',
    upstreamStatus: 'Upstream status',
    responseMode: 'Response mode',
    usage: 'Usage',
    output: 'Output',
    rawResponse: 'Raw response',
    diagnostics: 'diagnostics',
    optionalField: 'Optional field',
  },
  status: {
    enabled: 'enabled',
    off: 'off',
  },
  hints: {
    mode: 'Auto or pinned account.',
    account: 'Active accounts only.',
    sessionKey: 'Optional sticky key.',
    endpoint: 'Request shape.',
    model: 'Provider model id.',
    maxOutputTokens: 'Project cap: 1..4096.',
    includeRaw: 'Include bounded JSON.',
    prompt: 'Trimmed on submit.',
  },
  modes: {
    auto: 'Automatic',
    account: 'Account',
  },
  endpoints: {
    responses: 'Responses',
    chat_completions: 'Chat Completions',
  },
  actions: {
    run: 'Run probe',
    running: 'Waiting',
    reset: 'Clear result',
    integrationGuide: 'Integration guide',
    closeGuide: 'Close guide',
    closeGuideBackdrop: 'Close integration guide backdrop',
    openAccount: 'Open account',
    newAccount: 'New account',
    copyRawResponse: 'Copy raw response',
  },
  guide: {
    title: 'Integration guide',
    apiLabel: 'API',
    endpointLabel: 'Endpoint',
    apiKeyLabel: 'API key',
    apiKeyValue: 'empty',
    copy: 'Copy',
    tabs: {
      curl: 'cURL',
      python: 'Python',
      javascript: 'JavaScript',
      go: 'Go',
    },
  },
  validation: {
    textRequired: 'Prompt is required.',
    textMax: 'Prompt must be 16000 characters or fewer.',
    modelRequired: 'Model is required.',
    modelMax: 'Model must be 128 characters or fewer.',
    accountRequired: 'Choose an active account.',
    sessionKeyMax: 'Session key must be 128 characters or fewer.',
    maxOutputRange: 'Max output must be 1..4096.',
  },
  toasts: {
    success: 'Playground run complete',
    failed: 'Playground run failed',
  },
  errorTitle: 'Playground run failed',
  errors: {
    accountListUnavailable: 'Account list unavailable',
  },
  emptyOutput: 'No text returned.',
  emptyResult: 'No result yet.',
  emptyField: '—',
  accountStatus: {
    active: 'active',
    disabled: 'disabled',
  },
  authMethod: {
    api_key: 'API key',
    oauth_browser: 'OAuth browser',
    oauth_device: 'OAuth device',
    oauth_import: 'OAuth import',
  },
} as const
