export const strings = {
  eyebrow: 'Request log',
  stripe: '',
  titleLead: 'Trace every',
  titleStrong: 'LLM call',
  intro:
    'Search retained request records, inspect routing metadata, and open captured request or response bodies from one operator view.',
  filtersTitle: 'Filters',
  advancedFiltersTitle: 'Advanced Filter',
  advancedFiltersMeta: (count: number) => `${count} active`,
  tableTitle: 'Requests',
  columnsTitle: 'Columns',
  columnsMeta: (selected: number, total: number) => `${selected}/${total}`,
  detailTitle: 'Request Log Detail',
  listErrorTitle: 'Request log unavailable',
  optionsErrorTitle: 'Filter options unavailable',
  detailErrorTitle: 'Request detail unavailable',
  detailMetaIdle: 'select row',
  detailMetaLoading: 'loading',
  detailMetaReady: 'loaded',
  detailMetaError: 'failed',
  empty: 'No request records match the current filters.',
  loading: 'Loading request records',
  optionsLoading: 'Loading filter options',
  detailEmpty: 'Select a request row to inspect captured bodies.',
  bodyNotCaptured: 'Not captured for this request.',
  noFacets: 'No values',
  customRange: 'Custom range',
  flow: {
    title: 'Flow map',
    client: 'Client',
    router: 'Router',
    llmServer: 'LLM Server',
    responseRouter: 'response returned to router',
    clientToRouter: 'Client → Router',
    routerToServer: 'Router → LLM Server',
    serverToRouter: 'LLM Server → Router',
    baseURLNotCaptured: 'Base URL not captured',
  },
  labels: {
    search: 'Search',
    searchHint: 'Request id, client IP, path, model, session, method, or error code.',
    timeRange: 'Time range',
    time: 'Time',
    start: 'From',
    end: 'To',
    accounts: 'Accounts',
    outcomes: 'Outcomes',
    models: 'Models',
    responseModes: 'Response modes',
    pageSize: 'Page size',
    id: 'ID',
    createdAt: 'Time',
    requestId: 'Request ID',
    clientIp: 'Client IP',
    route: 'Route',
    account: 'Account',
    session: 'Session',
    model: 'Model',
    status: 'Status',
    outcome: 'Outcome',
    mode: 'Mode',
    tokens: 'Tokens',
    latency: 'Latency',
    totalLatency: 'Total',
    ttft: 'TTFT',
    error: 'Error',
    actions: 'Actions',
    columns: 'Columns',
    baseURL: 'Base URL',
    endpoint: 'Endpoint',
    provider: 'Provider',
    routerMetadata: 'Router metadata',
    tokenUsage: 'Token Usage',
    tokenUsageHelp: 'Token usage legend',
    inputTokens: 'Input',
    cachedInputTokens: 'Cached input',
    outputTokens: 'Output',
    reasoningTokens: 'Reasoning',
    totalTokens: 'Total',
  },
  actions: {
    apply: 'Apply',
    clear: 'Clear',
    reset: 'Reset',
    refresh: 'Refresh',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    previous: 'Previous',
    next: 'Next',
    clearCursor: 'Latest',
    open: 'Detail',
    close: 'Close',
    copy: 'Copy',
    copyRequestId: 'Copy request ID',
  },
  ranges: {
    all: 'All',
    hour: '1h',
    day: '24h',
    week: '7d',
    custom: 'Custom',
  },
  pagination: {
    current: (page: number) => `Current page ${page}`,
    page: (page: number) => `Page ${page}`,
    previous: 'Previous page',
    next: 'Next page',
  },
  timeBoundary: {
    custom: 'Custom',
    fromAny: 'From any',
    fromNow: 'From now',
    toNow: 'To now',
    customFrom: 'From custom',
    customTo: 'To custom',
    minutesAgo: (minutes: number) => `${minutes}m ago`,
    hoursAgo: (hours: number) => `${hours}h ago`,
    daysAgo: (days: number) => `${days}d ago`,
  },
  placeholders: {
    search: 'req_..., /v1/responses, gpt-5...',
  },
  emptyField: '-',
  copyDone: 'Copied',
  copyFailed: 'Copy failed',
} as const
