export const strings = {
  eyebrow: 'Account detail',
  parentTitle: 'Accounts',
  title: 'Account detail',
  subtitle:
    'Inspect account metadata, confirm the credential mode, and export a Codex-compatible auth.json for OAuth rows without opening the token payload in the UI.',
  loading: 'Loading account',
  invalidIdTitle: 'Invalid account id',
  invalidIdDetail:
    'The route parameter is not a positive integer, so the detail query was not sent.',
  summaryTitle: 'Account summary',
  metadataTitle: 'OAuth metadata',
  exportTitle: 'Export credentials',
  activateTitle: 'Activate account',
  disableTitle: 'Disable account',
  deleteTitle: 'Delete account',
  deleteHint:
    'Deletes this account from admin lists and removes it from routing or Playground eligibility.',
  actions: {
    exporting: 'Preparing auth.json…',
    export: 'Export auth.json',
    activate: 'Active account',
    activating: 'Activating account…',
    disable: 'Disable account',
    disabling: 'Disabling account…',
    delete: 'Delete account',
    confirmDelete: 'Confirm delete',
    deleting: 'Deleting account…',
  },
  labels: {
    id: 'Account id',
    name: 'Name',
    provider: 'Provider',
    authMethod: 'Auth method',
    status: 'Status',
    baseURL: 'Base URL',
    email: 'Email',
    plan: 'Plan',
    chatgptAccountID: 'ChatGPT account',
    lastRefresh: 'Last refresh',
    accessExpiresAt: 'Access expires at',
  },
  accountStatus: {
    active: 'Active',
    inactive: 'Inactive',
  },
  empty: '—',
  authMethod: {
    api_key: 'API key',
    oauth_browser: 'OAuth browser',
    oauth_device: 'OAuth device',
    oauth_import: 'OAuth import',
  },
  toasts: {
    exportSuccess: 'auth.json download started',
    exportFailed: 'Failed to export auth.json',
    activateSuccess: 'Account activated',
    activateFailed: 'Failed to activate this account',
    disableSuccess: 'Account disabled',
    disableFailed: 'Failed to disable this account',
    deleteSuccess: 'Account deleted',
    deleteFailed: 'Failed to delete this account',
  },
} as const
