export const strings = {
  eyebrow: 'Accounts overview',
  stripe: '',
  title: 'All Accounts',
  intro: 'OAuth cards surface email, plan label, and observed primary or secondary usage only.',
  loading: 'Loading accounts',
  empty: 'No accounts registered yet.',
  summaryTitle: 'Registered accounts',
  actions: {
    newAccount: 'Add account',
    openDetail: 'Open detail',
    activate: 'Active',
    activating: 'Activating…',
    disable: 'Disable',
    disabling: 'Disabling…',
  },
  labels: {
    authMethod: 'Auth method',
    status: 'Status',
    email: 'Email',
    plan: 'Plan',
    chatgptAccountID: 'ChatGPT account',
    lastRefresh: 'Last refresh',
    accessExpiresAt: 'Access expires at',
    baseURL: 'Base URL',
    primaryUsage: 'Primary used',
    secondaryUsage: 'Secondary used',
  },
  authMethod: {
    api_key: 'API key',
    oauth_browser: 'OAuth browser',
    oauth_device: 'OAuth device',
    oauth_import: 'OAuth import',
  },
  accountStatus: {
    active: 'Active',
    inactive: 'Inactive',
  },
  toasts: {
    activateSuccess: 'Account activated',
    activateFailed: 'Failed to activate this account',
    disableSuccess: 'Account disabled',
    disableFailed: 'Failed to disable this account',
  },
  emptyField: '—',
} as const
